# -*- coding: utf-8 -*-
"""24-09-02 watasi-tako.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DoE1AJ736ph8WjcBsLnCQW3_4dC8IMkJ
"""

print("저는 멍청합니다")

# many power mode 는 조심해서 사용하세요.